cli: fix argument parsing for pack-objects --stdout
The basename argument is unused when --stdout is used. Yet if no basename
was specified together with --stdout, the command was failing:

$ git rev-list main | dulwich pack-objects --stdout
Traceback (most recent call last):
  File "/home/stsp/dulwich/venv/bin/dulwich", line 33, in <module>
    sys.exit(load_entry_point('dulwich==0.20.50', 'console_scripts', 'dulwich')())
  File "/home/stsp/dulwich/venv/lib/python3.9/site-packages/dulwich/cli.py", line 784, in main
    return cmd_kls().run(argv[1:])
  File "/home/stsp/dulwich/venv/lib/python3.9/site-packages/dulwich/cli.py", line 533, in run
    basename = args[0]
IndexError: list index out of range